language: c

# Use newer travis container-based infrastructure
sudo: false

# Install flex dependency
addons:
  apt:
    packages:
      - flex
      - autoconf
      - libtool
      - asciidoc

# Build using gcc and clang since it is supported
compiler:
  - clang
  - gcc

# Probably a better way to do this TODO
before_script: autoreconf -fiv

# No configure or make install needed
# See c/Makefile for the reason for make -e
script: ./configure && make && make check
